export const USER = { id: 1, name: "fethi" };

export const GET_PRODUCTS_SUCCESS = "GET_PRODUCTS_SUCCESS";
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS";
export const UPDATE_PRODUCT_SUCCESS = "UPDATE_PRODUCT_SUCCESS";
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS";

export const GET_CATEGORIES_SUCCESS = "GET_CATEGORIES_SUCCESS";
export const CREATE_CATEGORY_SUCCESS = "CREATE_CATEGORIES_SUCCESS";
export const UPDATE_CATEGORY_SUCCESS = "UPDATE_CATEGORIES_SUCCESS";
export const DELETE_CATEGORY_SUCCESS = "DELETE_CATEGORY_SUCCESS";

export const GET_USER_SUCCESS = "GET_USER_SUCCESS";

export const GET_STOCKS_SUCCESS = "GET_STOCK_SUCCESS";
export const CREATE_STOCK_SUCCESS = "CREATE_STOCK_SUCCESS";
export const UPDATE_STOCK_SUCCESS = "UPDATE_STOCK_SUCCESS";
export const DELETE_STOCK_SUCCESS = "DELETE_STOCK_SUCCESS";

export const GET_STOCK_OPERATION_SUCCESS = "GET_STOCK_OPERATION_SUCCESS";

export const GET_UNIT_TYPES_SUCCESS = "GET_UNIT_TYPES_SUCCESS";
export const CREATE_UNIT_TYPE_SUCCESS = "CREATE_UNIT_TYPE_SUCCESS";
export const UPDATE_UNIT_TYPE_SUCCESS = "UPDATE_UNIT_TYPE_SUCCESS";
export const DELETE_UNIT_TYPE_SUCCESS = "DELETE_UNIT_TYPE_SUCCESS";

export const GET_STORES_SUCCESS = "GET_STORES_SUCCESS";
export const CREATE_STORE_SUCCESS = "CREATE_STORE_SUCCESS";
export const UPDATE_STORE_SUCCESS = "UPDATE_STORE_SUCCESS";
export const DELETE_STORE_SUCCESS = "DELETE_STORE_SUCCESS";

export const GET_ORDER_TYPES_SUCCESS = "GET_ORDER_TYPES_SUCCESS";

export const GET_ORDERS_SUCCESS = "GET_ORDERS_SUCCESS";
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";

export const GET_CUSTOMERS_SUCCESS = "GET_CUSTOMERS_SUCCESS";
export const CREATE_CUSTOMER_SUCCESS = "CREATE_CUSTOMER_SUCCESS";
export const UPDATE_CUSTOMER_SUCCESS = "UPDATE_CUSTOMER_SUCCESS";
export const DELETE_CUSTOMER_SUCCESS = "DELETE_CUSTOMER_SUCCESS";
